[CmdletBinding()]
param([string]$OutputDirectory = '_site')
$ErrorActionPreference = 'Stop'
Remove-Alias h -Force -ErrorAction SilentlyContinue
$root = Split-Path -Parent $PSScriptRoot; $site = Join-Path $root 'site'; $out = Join-Path $root $OutputDirectory
function Write-File { param([string]$Path,[AllowEmptyString()][string]$Content); $dir=Split-Path -Parent $Path; if($dir){New-Item $dir -ItemType Directory -Force|Out-Null}; [IO.File]::WriteAllText($Path,$Content,[Text.UTF8Encoding]::new($false)) }
function H { param([string]$Text) [Net.WebUtility]::HtmlEncode($Text) }
function Render-Md { param([string]$Markdown); $b=[Text.StringBuilder]::new(); $code=$false; $list=$false; $codeLines=@(); foreach($line in ($Markdown -split '\r?\n')) { if($line -match '^\s*```') { $code=-not $code; if(-not $code){[void]$b.Append('<pre><code>'+ (H ($codeLines -join "`n"))+'</code></pre>');$codeLines=@()} elseif($list){[void]$b.Append('</ul>');$list=$false}; continue }; if($code){$codeLines+=$line;continue}; if($line -match '^\s*#\s+(.+)$'){continue}; if($line -match '^\s*(#{1,6})\s+(.+)$'){if($list){[void]$b.Append('</ul>');$list=$false};$n=$Matches[1].Length;[void]$b.Append('<h'+$n+'>'+ (H $Matches[2])+'</h'+$n+'>');continue}; if($line -match '^\s*[-*+]\s+(.+)$'){if(-not$list){[void]$b.Append('<ul>');$list=$true};[void]$b.Append('<li>'+ (H $Matches[1])+'</li>');continue}; if($list){[void]$b.Append('</ul>');$list=$false}; if($line.Trim()){ $v=H ($line.Trim()); $v=[regex]::Replace($v,'`([^`]+)`','<code>$1</code>'); $v=[regex]::Replace($v,'\[([^]]+)\]\(([^)]+)\.md\)','<a href="$2.html">$1</a>'); [void]$b.Append('<p>'+ $v+'</p>') } }; if($list){[void]$b.Append('</ul>')};$b.ToString() }
function Prefix([string]$Path) { $dir=Split-Path -Parent($Path -replace '/','\'); if(-not$dir){return ''}; return (('../' * @($dir -split '[\\/]+' | Where-Object {$_}).Count) -join '') }
$documents=@(git -C $root ls-files | Where-Object {$_ -match '(?i)\.md$'} | ForEach-Object {$_ -replace '\\','/'} | Sort-Object);$manifest=@{generatedAt=(Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ');documents=$documents};Write-File (Join-Path $root 'docs-manifest.json') (($manifest|ConvertTo-Json -Depth 3)+"`n");if(Test-Path $out){Remove-Item $out -Recurse -Force};New-Item $out -ItemType Directory -Force|Out-Null;$cfg=Get-Content (Join-Path $site 'site.json') -Raw|ConvertFrom-Json;$tpl=Get-Content (Join-Path $site 'template.html') -Raw;$version=[DateTime]::UtcNow.Ticks.ToString()
$pages=@(foreach($d in $documents){$m=Get-Content (Join-Path $root ($d -replace '/','\')) -Raw;$t=if($m -match '(?m)^#\s+(.+)$'){$Matches[1]}else{[IO.Path]::GetFileNameWithoutExtension($d)};[pscustomobject]@{src=$d;out=([IO.Path]::ChangeExtension($d,'.html')).ToLowerInvariant();title=$t;html=(Render-Md $m)}})
function Render-Page { param([string]$Content,[string]$Title,[string]$Path);$tpl.Replace('{{DESCRIPTION}}',(H ([string]$cfg.description))).Replace('{{PAGE_TITLE}}',(H $Title)).Replace('{{SITE_TITLE}}',(H ([string]$cfg.title))).Replace('{{GITHUB_URL}}',$cfg.repository).Replace('{{ROOT_PREFIX}}',(Prefix $Path)).Replace('{{ASSET_VERSION}}',$version).Replace('{{CONTENT}}',$Content) }
$links=($pages|ForEach-Object{'<a class="category-card-link" data-search-card href="'+$_.out+'"><span>'+(H $_.title)+'</span><span>↗</span></a>'})-join"`n";$hero=($pages|Select-Object -First 2|ForEach-Object{'<a class="hero-link" href="'+$_.out+'">'+(H $_.title)+' ↗</a>'})-join'';$index='<main class="catalog-view"><section class="hero"><p class="eyebrow">'+(H ([string]$cfg.eyebrow))+'</p><h1>'+ (H ([string]$cfg.title))+'</h1><p class="hero-copy">'+(H ([string]$cfg.description))+'</p>'+ $hero+'</section><div class="catalog-toolbar"><form data-search-form><input class="search-input" id="site-search" type="search" placeholder="Search documentation"></form><div class="doc-count">'+$pages.Count+' documents</div></div><section class="category-grid"><article class="category-card" data-category="guides"><div class="category-card-head"><span class="category-icon">◇</span><strong>Documentation Library</strong></div><p>Browse application architecture, deployment, and security documentation.</p><span class="category-card-links">'+$links+'</span><span class="category-meta">'+$pages.Count+' documents →</span></article></section></main>';Write-File (Join-Path $out 'index.html') (Render-Page $index 'Home' 'index.html')
foreach($p in $pages){$content='<main class="reader-view"><div class="reader-navigation"><a class="back-button" href="'+(Prefix $p.out)+'index.html">← All documents</a><span>'+(H $p.src)+'</span></div><article class="reader"><div class="reader-tools"><span class="file-label">'+(H $p.src)+'</span><a class="github-link" href="'+$cfg.repository+'/blob/main/'+$p.src+'" target="_blank">View source on GitHub ↗</a></div><div class="markdown-body">'+$p.html+'</div></article></main>';Write-File (Join-Path $out ($p.out -replace '/','\')) (Render-Page $content $p.title $p.out)}
Write-File (Join-Path $out 'search-index.json') (($pages|ConvertTo-Json)+"`n");Copy-Item (Join-Path $site 'styles.css') (Join-Path $out 'styles.css');Copy-Item (Join-Path $site 'site.js') (Join-Path $out 'site.js');Write-File (Join-Path $out '.nojekyll') ''
